### PR TITLE
Account switcher

### PR DESCRIPTION
**Pull request by bastianallgeier**
### Summary of changes

- The default user is now called `admin` instead of `test`. You need to login with `admin@getkirby.com` and the default password now. 
- The lab environment shows the account switcher in the menu
- The lab environment now has three default users (admin, client and editor)
- The client role in the lab environment is setup to not have any users permissions

### CODE REVIEW

**Comment by distantnative** [comment]
I think in our environments class, accounts should also be now considered in the `::remove()` and `::store()` methods.

**Comment by distantnative** [comment]
@bastianallgeier Can I help somehow to wrap this up? What do you think about my suggestion?

**Comment by bastianallgeier** [comment]
@distantnative Sorry, I completely lost focus of this. Could you explain your suggestion to add it to the store and remove methods?

**Comment by distantnative** [comment]
@bastianallgeier I think what I meant is that we currently ignore `site/accounts/` when storing the current public folder into an environment. But with this change, it would actually be good to not ignore them any longer, but to store/save changes we make, if we make any.

**Comment by bastianallgeier** [comment]
Ah, now I get it. Makes total sense to me.

**Comment by distantnative** [comment]
@bastianallgeier Added it incl. a few tweaks. Please have a look if they make sense to you.

**Review by lukasbestle — COMMENTED** [review]
Very useful! On a quick glance the changes look good to me.

**Comment by bastianallgeier** [comment]
@distantnative the changes are great. 

I was just wondering if we use the old "test" user in some unit tests or in other places that we might have forgotten about. Do you have any memory if that could be the case?

**Comment by distantnative** [comment]
@bastianallgeier I think our unit tests should all be independent of the sandbox, right?

Otherwise, could be a users field or so, but cannot recall any.

**Comment by bastianallgeier** [comment]
Let's just merge it and see if something breaks :)

**Pull request merged**
